# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "gaka/gaka";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "gaka";
      groupId = "gaka";
      sha512 = "89e7e17360ff2b3414ba1d187db0abbedbffa6fa989a79cdcf63920050689bdbef9fd5f25691fc484d199ce6d5a97a9cbb4f8c07e70bc89eef33584e14cb5fb3";
      version = "0.3.0";

    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "a1805f07f6658982576dc1bfc0d9d34b23adebda3385739de116e8c4554b6ec824f07ffd070f32e767928923c6a695eea0cfb54cab3586ac8bce26700903cc5e";
      version = "1.4.0";

    };
    paths = [ src ];
  }

  ];
  }
  